# CS 549 Project

## Table Construction

In [2]:
import numpy as np
import pandas as pd

In [10]:
mendely1 = pd.read_csv("Phishing URLs.csv")
mendely1

                                                     url      Type
0      https://docs.google.com/presentation/d/e/2PACX...  Phishing
1        https://btttelecommunniccatiion.weeblysite.com/  Phishing
2                            https://kq0hgp.webwave.dev/  Phishing
3      https://brittishtele1bt-69836.getresponsesite....  Phishing
4             https://bt-internet-105056.weeblysite.com/  Phishing
...                                                  ...       ...
54802   http://www.ezblox.site/free/jennifer111/helpdesk  Phishing
54803  http://www.formbuddy.com/cgi-bin/formdisp.pl?u...  Phishing
54804  http://www.formbuddy.com/cgi-bin/formdisp.pl?u...  Phishing
54805       http://www.habbocreditosparati.blogspot.com/  Phishing
54806  http://creditiperhabbogratissicuro100.blogspot...  Phishing

[54807 rows x 2 columns]

In [12]:
mendely2 = pd.read_csv("URL dataset.csv")
mendely2

                                                      url        type
0                                  https://www.google.com  legitimate
1                                 https://www.youtube.com  legitimate
2                                https://www.facebook.com  legitimate
3                                   https://www.baidu.com  legitimate
4                               https://www.wikipedia.org  legitimate
...                                                   ...         ...
450171        http://ecct-it.com/docmmmnn/aptgd/index.php    phishing
450172  http://faboleena.com/js/infortis/jquery/plugin...    phishing
450173  http://faboleena.com/js/infortis/jquery/plugin...    phishing
450174                             http://atualizapj.com/    phishing
450175  http://writeassociate.com/test/Portal/inicio/I...    phishing

[450176 rows x 2 columns]

In [14]:
kaggleDf = pd.read_csv("malicious_phish.csv")
kaggleDf

                                                      url        type
0                                        br-icloud.com.br    phishing
1                     mp3raid.com/music/krizz_kaliko.html      benign
2                         bopsecrets.org/rexroth/cr/1.htm      benign
3       http://www.garage-pirenne.be/index.php?option=...  defacement
4       http://adventure-nicaragua.net/index.php?optio...  defacement
...                                                   ...         ...
651186            xbox360.ign.com/objects/850/850402.html    phishing
651187       games.teamxbox.com/xbox-360/1860/Dead-Space/    phishing
651188         www.gamespot.com/xbox360/action/deadspace/    phishing
651189      en.wikipedia.org/wiki/Dead_Space_(video_game)    phishing
651190          www.angelfire.com/goth/devilmaycrytonite/    phishing

[651191 rows x 2 columns]

In [24]:
mendely1 = mendely1.rename(columns={"Type": "type"})[['url', 'type']]

In [58]:
df = pd.concat([mendely1, mendely2, kaggleDf], ignore_index=True)
df = df.dropna(subset=['url', 'type'])
df = df.drop_duplicates(subset=['url']).reset_index(drop=True)
df

                                                       url      type
0        https://docs.google.com/presentation/d/e/2PACX...  Phishing
1          https://btttelecommunniccatiion.weeblysite.com/  Phishing
2                              https://kq0hgp.webwave.dev/  Phishing
3        https://brittishtele1bt-69836.getresponsesite....  Phishing
4               https://bt-internet-105056.weeblysite.com/  Phishing
...                                                    ...       ...
1144949            xbox360.ign.com/objects/850/850402.html  phishing
1144950       games.teamxbox.com/xbox-360/1860/Dead-Space/  phishing
1144951         www.gamespot.com/xbox360/action/deadspace/  phishing
1144952      en.wikipedia.org/wiki/Dead_Space_(video_game)  phishing
1144953          www.angelfire.com/goth/devilmaycrytonite/  phishing

[1144954 rows x 2 columns]

In [60]:
df['type'] = df['type'].str.lower()
df['type'] = df['type'].map({
    'legitimate': 0,
    'benign': 0,
    'phishing': 1,
    'malware': 1,
    'defacement': 1
})

In [70]:
df

                                                       url  type
0        https://docs.google.com/presentation/d/e/2PACX...     1
1          https://btttelecommunniccatiion.weeblysite.com/     1
2                              https://kq0hgp.webwave.dev/     1
3        https://brittishtele1bt-69836.getresponsesite....     1
4               https://bt-internet-105056.weeblysite.com/     1
...                                                    ...   ...
1144949            xbox360.ign.com/objects/850/850402.html     1
1144950       games.teamxbox.com/xbox-360/1860/Dead-Space/     1
1144951         www.gamespot.com/xbox360/action/deadspace/     1
1144952      en.wikipedia.org/wiki/Dead_Space_(video_game)     1
1144953          www.angelfire.com/goth/devilmaycrytonite/     1

[1144954 rows x 2 columns]

In [74]:
df['type'].unique()

array([1, 0])

## Feature Engineering

In [86]:
import math
import re
from urllib.parse import urlparse

from sklearn.feature_extraction.text import TfidfVectorizer

In [87]:
df

                                                       url  type
0        https://docs.google.com/presentation/d/e/2PACX...     1
1          https://btttelecommunniccatiion.weeblysite.com/     1
2                              https://kq0hgp.webwave.dev/     1
3        https://brittishtele1bt-69836.getresponsesite....     1
4               https://bt-internet-105056.weeblysite.com/     1
...                                                    ...   ...
1144949            xbox360.ign.com/objects/850/850402.html     1
1144950       games.teamxbox.com/xbox-360/1860/Dead-Space/     1
1144951         www.gamespot.com/xbox360/action/deadspace/     1
1144952      en.wikipedia.org/wiki/Dead_Space_(video_game)     1
1144953          www.angelfire.com/goth/devilmaycrytonite/     1

[1144954 rows x 2 columns]

### Keyword Extraction

In [107]:
KEYWORDS = [
    "pay", "ticket", "fine", "refund", "claim", "submit", "verify", "update",
    "account", "login", "secure", "reset", "password", "invoice", "shipping",
    "delivery", "package"
]

keyword_pattern = re.compile("|".join(KEYWORDS), re.IGNORECASE)

def keyword_count(url: str):
    matches = keyword_pattern.findall(url)
    return len(matches)

df["keyword_count"] = df["url"].apply(keyword_count)
df.head()

                                                 url  type  keyword_count
0  https://docs.google.com/presentation/d/e/2PACX...     1              0
1    https://btttelecommunniccatiion.weeblysite.com/     1              0
2                        https://kq0hgp.webwave.dev/     1              0
3  https://brittishtele1bt-69836.getresponsesite....     1              0
4         https://bt-internet-105056.weeblysite.com/     1              0

In [108]:
df['keyword_count'].unique()

array([ 0,  2,  1,  3,  4,  5,  7,  6, 12,  8, 16, 14, 15, 10, 13, 11, 18,
        9])